server:
  servlet:
    context-path: /api/karv-coins

spring:
  application:
    name: karv-coins
  datasource:
    url: jdbc:postgresql://ep-autumn-hall-acokcx3b-pooler.sa-east-1.aws.neon.tech/db-karv-coins-des?sslmode=require&channelBinding=require
    username: karv-coins-db-owner
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwt:
      issuer: karv-coins
      expiration-seconds: 3600
      secret: ${JWT_SECRET:jwtsecretasdasdasdsd}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
